export const ADD_OPTION = "ADD_OPTION";
export const SELECTED_OPTION = "SELECTED_OPTION";
export const REMOVE_ALL_OPTIONS = "REMOVE_ALL_OPTIONS";
export const REMOVE_OPTION = "REMOVE_OPTION";
export const HIDE_MODAL = "HIDE_MODAL";
